### ISSUE TITLE
platform enums do not list all possible values

### ISSUE THREAD

**Issue by abgeorge7** [kids-first/kf-api-dataservice#557] opened 2020-10-15 14:18 UTC
Under `sequencing_experiment`, `platform` is restricted to a list of values, but some studies have platforms that are not listed here. This field is necessary for harmonization, so it is important that it is accurate. Can it be free text instead?

**Comment by fiendish** [comment] 2020-12-24 06:11
probably a duplicate of #498

**Closed as completed** 2023-05-08 18:59 UTC
Labels: data model
